name: Test Action
on:
  workflow_dispatch:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
      - run: git status --porcelain
      - name: Keep previous test value
        id: previous
        run: echo '::set-output name=value::${{ secrets.GHA_SECRETS_TEST }}'
      - name: Gen new random Secret
        id: new
        run: echo "::set-output name=value::$(tr -dc 'a-zA-Z0-9' < /dev/random | head -c10)"
      - uses: ./.
        with:
          token: ${{ secrets.TOKEN }}
          name: 'GHA_SECRETS_TEST'
          value: ${{ steps.new.outputs.value }}
      - run: echo "${{ secrets.GHA_SECRETS_TEST }}" | md5sum
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.GHA_SECRETS_TEST }}" | md5sum
  test3:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo "${{ secrets.GHA_SECRETS_TEST }}" | md5sum